name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install packages
      run: npm install
    - name: Deploy to Github Pages
      run: |
        git config user.email $EMAIL
        git config user.name $USER
        git remote set-url origin https://x-access-token:$ACCESS_TOKEN@github.com/$GITHUB_REPOSITORY
        npm run deploy
      env:
        CI: true
        EMAIL: ${{ secrets.EMAIL }}
        USER: ${{ secrets.USER }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}